name: CI
on:

  push:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          CURRENT_TIME_STAMP=$(date "+%Y.%m.%d-%H.%M.%S")
          TAG=${CURRENT_TIME_STAMP}
          echo "TAG: $TAG"
          echo test=$TAG >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}
