name: Pull Request Review for Production
on:
  pull_request:
    types: [closed]
    branches:
      - release-*
  create:
    branches:
      - release-*
jobs:
# Run a job to tag @atharvaunde to request review using the PR title
  tag_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Reviewers
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = context.payload.pull_request
            const title = pr.title
            const body = pr.body
            const reviewers = ['atharva', 'visa']
            const reviewRequest = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              reviewers: reviewers
            }
            await github.pulls.createReviewRequest(reviewRequest)
            const comment = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `@${reviewers.join(' @')} Please review this PR`
            }
            await github.issues.createComment(comment)

